---
# - name: Create ssh key
#   hosts: client
#   remote_user: root

#   tasks:
#   - name: SSH KeyGen command
#     shell: > 
#      ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
#      creates="~/.ssh/id_rsa"

#   - name: Fetch the keyfile from one server to another
#     fetch: 
#       src: "~/.ssh/id_rsa.pub"
#       dest: "buffer/client-id_rsa.pub"
#       flat: yes




# - name: Copy ssh key
#   hosts: backup-server
#   remote_user: root


#   tasks:
#   - name: Copy the key add to authorized_keys using Ansible module
#     authorized_key:
#       user: root
#       state: present
#       key: "{{ lookup('file','buffer/client-id_rsa.pub')}}"
  


- hosts: client
  name: Setup client
  become: yes
  roles:
    - role: client

- hosts: backup-server
  name: Setup backup-server
  become: yes
  roles:
    - role: backup-server

